### ISSUE TITLE
With large number of tabs, tab center scrolls jankily

### ISSUE THREAD

**Issue by mystor** [bwinton/TabCenter#273]
When I have a large number of tabs, tab center appears to scroll randomly as it is opening or closing, causing the tabs to jerk up and down, and causing me to lose my place in the tab list. It would be better if they didn't scroll in this situation.

**Comment by Qhuea** [comment]
@mystor I don't see this issue...

**Comment by mystor** [comment]
Here's a zip with a mov file showing the janky behavior. 

[janky scroll.mov.zip](https://github.com/bwinton/VerticalTabs/files/279731/janky.scroll.mov.zip)

**Comment by ericawright** [comment]
might be a dupe of #245, the selected tab is trying to get into view. #245 has been fixed and will be out with next release.

**Comment by chris-morgan** [comment]
Still an issue. And combined with certain touch-based issues (where expansion only happens when you tap on something, but *before it decides what it is you tapped on*, thus potentially changing what you actually tapped on), this becomes *super* annoying, and fairly close to genuinely completely unusable even with determination.

For pointer devices this is very annoying; for touch devices it’s utterly crippling.

**Comment by devanes** [comment]
What I notice (having about 100-200 tabs in a window) is that when clicking on a tab, the bar seems to scroll to the position of the **previously** selected tab, instead of the position of the new one.

**Comment by chris-morgan** [comment]
Just got an update, and it’s gone from being terrible to unbearable. Scrolling is now close enough to useless, it just jumps all over the place.

At this point, I think I’m going to have to go back to Tree Style Tab for a while.

**Comment by roryokane** [comment]
@devanes The issue you describe is tracked in issue #492.
